# dev environment config

input:
  # city_path: s3a://YOUR_S3_BUCKET_NAME/top-produce/data/city_info.csv
  # produce_path: s3a://YOUR_S3_BUCKET_NAME/top-produce/data/product_info.parquet
  # user_visit_action_path: s3a://YOUR_S3_BUCKET_NAME/top-produce/data/user_visit_action.parquet
  
  city_path: file:///mnt/e/Top-produce-ETL/test_data/city_info.csv
  produce_path: file:///mnt/e/Top-produce-ETL/test_data/product_info.csv
  # user_visit_action_path: file:///mnt/e/Top-produce-ETL/test_data/user_visit_action.csv
  # TODO: Replace YOUR_S3_BUCKET_NAME with your actual bucket name below
  user_visit_action_path: s3a://YOUR_S3_BUCKET_NAME/user_action/

output:
  path: file:///mnt/e/Top-produce-ETL/test_data/output/