env: dev

input:
  source_type: s3
  city_path: s3a://myjustinbucket51562/top-produce/data/city_info.csv
  produce_path: s3://myjustinbucket51562/top-produce/data/product_info.parquet
  user_visit_action_path: s3://myjustinbucket51562/top-produce/data/user_visit_action.parquet

output:
  path: s3://myjustinbucket51562/output/top_products/

processing:
  group_by_column: region
  target_metric: sales
  top_n: 3
